config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

# Defines the root path route ("/")
# root "articles#index"
Rails.application.routes.draw do
  root to: "main#index" 
  # get "about", to: "about#index" 
  get "about-us", to: "about#index", as: :about

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"

  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  delete "logout", to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, format: {
                                        with: /\A[^@\/\s]+@[^@\/\s]+\z/,
                                        message: "must be a valid email" } 
    validates :password_confirmation, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Run this before running other methods, 
    # like index in MainController
    before_action :set_current_user 

    def set_current_user
        if session[:user_id]
            # @curr_user = User.find_by(id: session[:user_id])
            Current.user = User.find_by(id: session[:user_id])
        end
    end

    def require_user_logged_in!
        redirect_to sign_in_path, alert: "You must be signed in to do that" if Current.user.nil?
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new
    end

    def create
        @user = User.find_by(email: params[:email])
        if @user.present? 
            # Send email in background
            # deliver_now will make your rails app slow to respond
            PasswordMailer.with(user: @user).reset.deliver_now        
        end
        
        # Always do a redirect coz we don't want anyone to know 
        # if that account actually exits in your DB,
        # As this allows for dictionary attacks
        redirect_to root_path, notice: "If the user exists, password reset request is sent to your email!"
    end

    def edit 
        @user = User.find_signed!(params[:token], purpose: "password_reset")
        rescue ActiveSupport::MessageVerifier::InvalidSignature
            redirect_to sign_in_path, alert: "Your token has expired! Please try again..."
    end

    def update 
        @user = User.find_signed!(params[:token], purpose: "password_reset")
        if @user.update(password_params) 
            redirect_to sign_in_path, notice: "Your password was reset successfully. Please sign in!"
        else
            render :edit, status: :unprocessable_entity
        end
    end

    private
    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end

end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :require_user_logged_in!

    def edit
    end

    def update
        if Current.user.update(password_params)
            redirect_to root_path, notice: "Password Updated"
        else 
            render :edit, status: :unprocessable_entity
        end
    end

    private
    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def new
        @new_user = User.new 
    end
    def create
        # render plain: params[:user] # Renders simple text
        # Similar to User.new(email: "...", password: "...", password_confirmation: "...")
        # @user = User.new(params[:user]) # NOT SECURE
        @new_user = User.new(user_params)
        if @new_user.save # If user is saved to the database, go to home page
            session[:user_id] = @new_user.id
            redirect_to root_path , notice: "Successfuly created account"
        else # Else render the new signup page again
            render :new, status: :unprocessable_entity
        end
    end
    # Create a private helper method to 
    private
    def user_params
        # params[:user] # Same thing but no error handling
        # params.require(:user) # Raises an error if user not found
        params.require(:user).permit(:email, :password, :password_confirmation) # These are 
                                                                # the only things allowd to set
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new 
    end

    def create 
        # One thing to note here is that params returned is not hash of hashes
        # But a simple hash with keys 
        curr_user = User.find_by(email: params[:email])
        if curr_user.present? && curr_user.authenticate(params[:password])
            session[:user_id] = curr_user.id
            redirect_to root_path, notice: "Logged in successfully"
        else 
            flash[:alert] = "Invalid email or password"
            render :new, status: :unprocessable_entity
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1> About us </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduledTweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <div class="container">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
    <h1> Welcome to Scheduled Tweets </h1>
</div>

<!-- <% if Current.user %>
    Logged in as <%= Current.user.email %>
     # <%= link_to "Logout", logout_path, method: :delete %> 
    <%= button_to "Logout", logout_path, method: :delete %> 
<% end %> -->

 

app/views/password_resets/edit.html.erb
<h1> Reset your password </h1>

<%= form_with model: @user,  url:password_reset_edit_path(token: params[:token]) do |form| %>
    <% if form.object.errors.any? %>
        <div class="alert alert-danger">
            <!-- Print each error message, inside a div -->
            <% form.object.errors.full_messages.each do |message| %>
               <div> <%= message %> </div> 
            <% end %>
        </div>
    <% end %>
    <!-- 2 fields for password and password_confirmation -->
    <div class="mb-3">
        <%= form.label :password %>
        <%= form.password_field :password, class: "form-control", placeholder: "password"%> 
    </div>
    <div class="mb-3">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, class: "form-control", placeholder: "password"%> 
    </div>
    <div class="mb-3">
        <%= form.submit "Reset Password", class: "btn btn-primary"%>
    </div>
<%  end %>

app/views/password_resets/new.html.erb
<h1> Forgot your password? </h1>

<%= form_with  url:password_reset_path do |form| %>

    <div class="mb-3">
        <%= form.label :email %>
        <%= form.text_field :email, class: "form-control", placeholder: "steve@email.com"%> 
    </div>
    <div class="mb-3">
        <%= form.submit "Reset Password", class: "btn btn-primary"%>
    </div>
<%  end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %> <!-- Doesnt have = coz we dont want to return value in html -->
    <div class="alert alert-info mt-4" role="alert"> <!-- alert, blue, margin-top 4 -->
        <%= flash[:notice] %>
    </div>
<%end%>

<% if flash[:alert] %> <!-- Doesnt have = coz we dont want to return value in html -->
    <div class="alert alert-warning mt-4" role="alert">
        <%= flash[:alert] %>
    </div>
<%end%>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "NavBar", root_path, class: "navbar-brand" %>
  <!-- <a class="navbar-brand" href="#">Navbar</a> -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">

      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
        <!-- <a class="nav-link" href="/">Home</a> -->
      </li>

      <li class="nav-item">
        <%= link_to "About", about_path, class: "nav-link" %>
        <!-- <a class="nav-link" href="/about">About</a> -->
      </li>
     
    </ul>

    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
      <% if Current.user %>        
        <li class="nav-item">
          <!-- <span class="navbar-text"><%= Current.user.email %></span>  -->
          <%= link_to Current.user.email , edit_password_path %>
        </li>
        <li class="nav-item">
          <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-outline-secondary" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", sign_up_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", sign_in_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>

</nav>